<?php 
require_once __DIR__ . '/includes/header-new.php';
?>
<body>
    <!-- Header -->
    <?php require_once __DIR__ . '/includes/nav-new.php'; ?>
    <div class="policy-container">
        <div class="policy-header">
            <h1>Terms of Service</h1>
            <p class="last-updated"><strong>Last Updated:</strong> March 1, 2026</p>
        </div>

        <div class="policy-section">
            <h2>1. Acceptance of Terms</h2>
            <p>Welcome to Petawall ("Company," "we," "our," or "us"). By accessing or using our cybersecurity assessment platform and related services (the "Platform"), you agree to be bound by these Terms of Service (the "Terms"). If you are using the Platform on behalf of an organization, you represent that you have authority to bind that organization to these Terms.</p>
            <p class="important-notice"><strong>IF YOU DO NOT AGREE TO THESE TERMS, YOU MAY NOT ACCESS OR USE THE PLATFORM.</strong></p>
        </div>

        <div class="policy-section">
            <h2>2. Definitions</h2>
            <ul>
                <li><strong>"Platform":</strong> Our cybersecurity assessment tools and services, including but not limited to vulnerability scanning, waf analyzer, phishing analysis, code analysis, mobile app scanning, IoT device discovery, and related services.</li>
                <li><strong>"User", "You":</strong> Any individual or entity accessing or using the Platform.</li>
                <li><strong>"Organization":</strong> The company, government entity, or other legal entity on whose behalf you use the Platform.</li>
                <li><strong>"Content":</strong> Any data, information, code, files, or materials you submit to or through the Platform.</li>
                <li><strong>"Results":</strong> The analysis, reports, findings, and recommendations generated by the Platform based on your Content.</li>
                <li><strong>"Authorized User":</strong> Individuals within your Organization authorized to access the Platform under your subscription.</li>
            </ul>
        </div>

        <div class="policy-section">
            <h2>3. Account Registration and Security</h2>
            
            <h3>3.1 Account Creation</h3>
            <p>You must create an account to access the Platform. You agree to:</p>
            <ul>
                <li>Provide accurate, current, and complete information.</li>
                <li>Maintain and update your information promptly.</li>
                <li>Keep your account credentials confidential.</li>
                <li>Not share your account with unauthorized users.</li>
                <li>Not use another user's account without permission.</li>
            </ul>

            <h3>3.2 Account Security</h3>
            <p>You are responsible for all activity that occurs under your account. You must notify us immediately of any unauthorized access or security breach at <a href="mailto:support@petawall.com">support@petawall.com</a>.</p>

            <h3>3.3 Account Type</h3>
            <ul>
                <li><strong>Individual Account:</strong> Individual professional or organization can register as an entity with a single account.</li>
            </ul>
        </div>

        <div class="policy-section">
            <h2>4. Subscription and Payment</h2>
            
            <h3>4.1 Subscription Plans</h3>
            <p>We offer various subscription plans with different features and usage limits. Details are available on our Pricing page.</p>

            <h3>4.2 Fees and Payment</h3>
            <ul>
                <li>Fees are as specified at the time of purchase.</li>
                <li>Payments are due in advance and are non-refundable except as required by law.</li>
                <li>We accept major credit cards and may offer invoicing for customers.</li>
                <li>You authorize us to charge your payment method for all applicable fees.</li>
            </ul>

            <h3>4.3 Free Trials</h3>
            <p>We may offer free trials. Upon trial expiration, access will be suspended unless you upgrade to a paid subscription.</p>

            <h3>4.4 Renewals and Cancellation</h3>
            <ul>
                <li>Subscriptions automatically renew unless cancelled before the renewal date.</li>
                <li>You may cancel through your account settings or by contacting support.</li>
                <li>Cancellation is effective at the end of the current billing period.</li>
            </ul>

            <h3>4.5 Fee Changes</h3>
            <p>We may change fees with 30 days' notice. Continued use after the change constitutes acceptance.</p>
        </div>

        <div class="policy-section">
            <h2>5. Use of the Platform</h2>
            
            <h3>5.1 Permitted Use</h3>
            <p>Subject to these Terms, we grant you a non-exclusive, non-transferable, revocable license to access and use the Platform for your internal business purposes.</p>

            <h3>5.2 User Content</h3>
            <p>You retain all rights to your Content. You grant us a limited license to process, analyze, and store your Content solely to provide the Platform services.</p>
            <p><strong>You represent and warrant that:</strong></p>
            <ul>
                <li>You own or have necessary rights to your Content.</li>
                <li>Your Content does not violate any laws or third-party rights.</li>
                <li>You have obtained all necessary consents for any personal data in your Content.</li>
            </ul>

            <h3>5.3 Prohibited Conduct</h3>
            <p><strong>You agree NOT to:</strong></p>
            
            <p><strong>Misuse the Platform:</strong></p>
            <ul>
                <li>Use the Platform for illegal purposes or to violate any laws.</li>
                <li>Attempt to gain unauthorized access to the Platform or its systems.</li>
                <li>Interfere with or disrupt the integrity or performance of the Platform.</li>
                <li>Reverse engineer, decompile, or disassemble the Platform.</li>
                <li>Circumvent any access or use restrictions.</li>
            </ul>

            <p><strong>Misuse Security Tools:</strong></p>
            <ul>
                <li>Use the tools against systems you do not own or have explicit permission to test.</li>
                <li>Use phishing simulation tools without proper authorization and consent.</li>
                <li>Upload malware or malicious code to test our Platform.</li>
                <li>Use assessment results for illegal purposes (e.g., to exploit discovered vulnerabilities without authorization).</li>
            </ul>

            <p><strong>Content Restrictions:</strong></p>
            <ul>
                <li>Upload Content that contains viruses, worms, or other malicious code.</li>
                <li>Submit Content that infringes intellectual property rights.</li>
                <li>Include sensitive personal data without proper safeguards (e.g., health information, government IDs).</li>
            </ul>

            <h3>5.4 Acceptable Use Policy (AUP)</h3>
            <p>You must comply with our Acceptable Use Policy, which prohibits:</p>
            <ul>
                <li>Testing systems without authorization ("unauthorized penetration testing").</li>
                <li>Using our Platform to conduct attacks on third parties.</li>
                <li>Distributing assessment results of systems you do not own.</li>
            </ul>
        </div>

        <div class="policy-section">
            <h2>6. Intellectual Property Rights</h2>
            
            <h3>6.1 Our IP</h3>
            <p>The Platform, including its software, algorithms, methodology, reports (excluding your Content), and documentation, is owned by us or our licensors and protected by intellectual property laws.</p>

            <h3>6.2 Feedback</h3>
            <p>If you provide suggestions, ideas, or feedback, you grant us a perpetual, irrevocable, royalty-free license to use them without restriction.</p>

            <h3>6.3 Usage Data</h3>
            <p>We may collect and use aggregated, anonymized data to improve our services and develop new features. This data cannot identify you or your Organization.</p>
        </div>

        <div class="policy-section">
            <h2>7. Confidentiality</h2>
            
            <h3>7.1 Definition</h3>
            <p>"Confidential Information" means any non-public information disclosed by one party to the other, including:</p>
            <ul>
                <li>Your assessment data, reports, and security findings.</li>
                <li>Our proprietary algorithms, methodologies, and pricing.</li>
                <li>Business strategies and technical information.</li>
            </ul>

            <h3>7.2 Obligations</h3>
            <p>Each party agrees to:</p>
            <ul>
                <li>Use Confidential Information only for purposes of these Terms.</li>
                <li>Protect Confidential Information with reasonable care.</li>
                <li>Not disclose Confidential Information to third parties except as necessary to perform services.</li>
            </ul>

            <h3>7.3 Exclusions</h3>
            <p>Confidential Information does not include information that:</p>
            <ul>
                <li>Is or becomes publicly available without breach.</li>
                <li>Was rightfully in recipient's possession before disclosure.</li>
                <li>Is independently developed without use of Confidential Information.</li>
            </ul>

            <h3>7.4 Security Researchers</h3>
            <p>If you are using our Platform for legitimate security research, you agree to follow responsible disclosure practices and not publicly disclose vulnerabilities without coordination.</p>
        </div>

        <div class="policy-section">
            <h2>8. Disclaimer of Warranties</h2>
            <p class="important-notice"><strong>THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND.</strong></p>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING:</p>
            <ul>
                <li>MERCHANTABILITY</li>
                <li>FITNESS FOR A PARTICULAR PURPOSE</li>
                <li>NON-INFRINGEMENT</li>
                <li>ACCURACY OR COMPLETENESS OF RESULTS</li>
                <li>UNINTERRUPTED OR ERROR-FREE SERVICE</li>
            </ul>
            <p><strong>IMPORTANT:</strong></p>
            <ul>
                <li>Security tools may produce false positives or false negatives.</li>
                <li>Results should be verified by qualified professionals before making security decisions.</li>
                <li>Our assessments are not a substitute for comprehensive security audits or penetration testing.</li>
            </ul>
        </div>

        <div class="policy-section">
            <h2>9. Limitation of Liability</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW:</p>
            
            <h3>9.1 No Indirect Damages</h3>
            <p>NEITHER PARTY WILL BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, DATA LOSS, OR BUSINESS INTERRUPTION.</p>

            <h3>9.2 Liability Cap</h3>
            <p>OUR TOTAL LIABILITY ARISING OUT OF OR RELATED TO THESE TERMS WILL NOT EXCEED THE AMOUNT PAID BY YOU DURING THE TWELVE (12) MONTHS PRECEDING THE CLAIM.</p>

            <h3>9.3 Exceptions</h3>
            <p>Nothing in these Terms limits liability for:</p>
            <ul>
                <li>Fraud or fraudulent misrepresentation</li>
                <li>Death or personal injury caused by negligence</li>
                <li>Gross negligence or willful misconduct</li>
                <li>Any liability that cannot be limited by applicable law</li>
            </ul>

            <h3>9.4 Security Testing Risks</h3>
            <p>YOU ACKNOWLEDGE THAT SECURITY TESTING TOOLS CARRY INHERENT RISKS, INCLUDING POTENTIAL SERVICE DISRUPTION. YOU ARE RESPONSIBLE FOR:</p>
            <ul>
                <li>Conducting tests in controlled environments</li>
                <li>Obtaining proper authorization before testing</li>
                <li>Having rollback and recovery procedures</li>
            </ul>
        </div>

        <div class="policy-section">
            <h2>10. Indemnification</h2>
            <p>You agree to indemnify, defend, and hold harmless Petawall, its affiliates, and their respective officers, directors, employees, and agents from any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising out of or relating to:</p>
            <ul>
                <li>Your Content or its use.</li>
                <li>Your violation of these Terms.</li>
                <li>Your unauthorized use of the Platform.</li>
                <li>Your violation of any third-party rights, including intellectual property or privacy rights.</li>
                <li>Your failure to obtain proper authorization before testing systems.</li>
            </ul>
        </div>

        <div class="policy-section">
            <h2>11. Termination</h2>
            
            <h3>11.1 By You</h3>
            <p>You may terminate your account at any time through account settings or by contacting support.</p>

            <h3>11.2 By Us</h3>
            <p>We may suspend or terminate your access immediately without notice if:</p>
            <ul>
                <li>You breach these Terms.</li>
                <li>We suspect fraudulent or illegal activity.</li>
                <li>Required by law or regulatory authority.</li>
                <li>You fail to pay fees when due.</li>
            </ul>

            <h3>11.3 Effect of Termination</h3>
            <p>Upon termination:</p>
            <ul>
                <li>Your right to access the Platform ceases.</li>
                <li>We may delete your Content after 30 days (subject to legal holds).</li>
                <li>Sections 6, 7, 8, 9, 10, 11, and 12 survive.</li>
            </ul>
        </div>

        <div class="policy-section">
            <h2>12. Governing Law and Dispute Resolution</h2>
            
            <h3>12.1 Governing Law</h3>
            <p>These Terms are governed by the laws of United Kingdom, without regard to conflict of laws principles.</p>

            <h3>12.2 Dispute Resolution</h3>
            <p><strong>Informal Resolution:</strong> Before filing a claim, parties will attempt to resolve disputes informally by contacting the other party.</p>
            <p><strong>Arbitration:</strong> Any dispute not resolved informally will be resolved by binding arbitration in accordance with the rules of the United Kingdom Arbitration Association (or equivalent body in your jurisdiction).</p>
            <p><strong>Class Action Waiver:</strong> Disputes must be brought on an individual basis only. No class actions, representative actions, or consolidated proceedings are permitted.</p>
            <p><strong>Location:</strong> Arbitration will be held in London, England or virtually.</p>

            <h3>12.3 Injunctive Relief</h3>
            <p>Nothing in this section prevents either party from seeking injunctive or equitable relief in court to protect intellectual property or Confidential Information.</p>
        </div>

        <div class="policy-section">
            <h2>13. Compliance with Laws</h2>
            
            <h3>13.1 Export Controls</h3>
            <p>You agree to comply with all applicable export and import laws, including United Kingdom Export Administration Regulations. You represent that you are not:</p>
            <ul>
                <li>Located in a country subject to U.K. embargo.</li>
                <li>On any U.K. government restricted parties list.</li>
            </ul>

            <h3>13.2 Anti-Corruption</h3>
            <p>You agree not to violate any anti-corruption laws, including the U.K. Foreign Corrupt Practices Act.</p>

            <h3>13.3 Data Protection</h3>
            <p>You agree to comply with all applicable data protection laws, including GDPR, CCPA, and others, when using the Platform.</p>
        </div>

        <div class="policy-section">
            <h2>14. Changes to Terms</h2>
            <p>We may modify these Terms at any time. We will notify you of material changes by:</p>
            <ul>
                <li>Email to your registered address</li>
                <li>Notice within the Platform</li>
                <li>Posting updated Terms with revised date</li>
            </ul>
            <p>Your continued use after changes constitutes acceptance.</p>
        </div>

        <div class="policy-section">
            <h2>15. General Provisions</h2>
            
            <h3>15.1 Entire Agreement</h3>
            <p>These Terms constitute the entire agreement between you and us regarding the Platform.</p>

            <h3>15.2 Severability</h3>
            <p>If any provision is found unenforceable, the remaining provisions remain in effect.</p>

            <h3>15.3 Waiver</h3>
            <p>Failure to enforce any right does not constitute a waiver.</p>

            <h3>15.4 Assignment</h3>
            <p>You may not assign these Terms without our consent. We may assign without restriction.</p>

            <h3>15.5 Force Majeure</h3>
            <p>Neither party is liable for delays or failures due to causes beyond reasonable control.</p>

            <h3>15.6 Notice</h3>
            <p>Notices will be sent to the email address in your account or to our registered address.</p>
        </div>

        <div class="policy-section contact-section">
            <h2>16. Contact Information</h2>
            <ul>
                <li><strong>Support:</strong> <a href="mailto:support@petawall.com">support@petawall.com</a></li>
            </ul>
            <p><strong>Address:</strong> 85 Great Portland Street, London, W1W 7LT, United Kingdom</p>
        </div>
    </div>
<!-- Login Modal -->
    <?php require_once __DIR__ . '/includes/login-modal.php'; ?>
    
    <!-- Footer -->
    <?php require_once __DIR__ . '/includes/footer.php'; ?>

    <script src="assets/js/auth.js"></script>
    <link rel="stylesheet" href="assets/styles/legal.css">
    <link rel="stylesheet" href="assets/styles/modal.css">
</body>
</html>