<?php
class EmailService {
    private $pdfGenerator;
    private $emailGateway;
    
    public function __construct($emailGateway = null) {
        $this->pdfGenerator = new PdfReportGenerator();
        $this->emailGateway = $emailGateway ?? new ZeptoMailGateway();
    }
    
    public function sendVulnerabilityReport($recipients, $scanData, $results) {
        try {
            // Generate PDF report
            $pdfPath = $this->pdfGenerator->generateVulnerabilityReport($scanData, $results);
            
            // Prepare email content
            $subject = $this->generateEmailSubject($scanData, $results);
            $body = $this->generateEmailBody($scanData, $results);
            
            // Send email with PDF attachment
            $result = $this->sendEmailWithAttachment(
                $recipients, 
                $subject, 
                $body, 
                $pdfPath
            );
            
            // Clean up temporary file
            if (file_exists($pdfPath)) {
                unlink($pdfPath);
            }
            
            return $result;
            
        } catch (Exception $e) {
            error_log("Failed to send vulnerability report: " . $e->getMessage());
            return false;
        }
    }
    
    private function generateEmailSubject($scanData, $results) {
        $summary = $results['summary'] ?? [];
        $totalVulns = array_sum($summary);
        $criticalCount = $summary['critical'] ?? 0;
        
        $subject = "Vulnerability Scan Report - {$scanData['target_url']}";
        
        if ($criticalCount > 0) {
            $subject .= " - {$criticalCount} CRITICAL vulnerabilities";
        } elseif ($totalVulns > 0) {
            $subject .= " - {$totalVulns} vulnerabilities found";
        } else {
            $subject .= " - No vulnerabilities found";
        }
        
        return $subject;
    }
    
    private function generateEmailBody($scanData, $results) {
        $summary = $results['summary'] ?? [];
        $critical = $summary['critical'] ?? 0;
        $high = $summary['high'] ?? 0;
        $medium = $summary['medium'] ?? 0;
        $low = $summary['low'] ?? 0;
        $total = $critical + $high + $medium + $low;
        
        return "
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
                .header { background: #f8f9fa; padding: 20px; border-radius: 5px; }
                .summary-card { display: inline-block; margin: 10px; padding: 15px; border-radius: 5px; color: white; }
                .critical { background: #dc3545; }
                .high { background: #fd7e14; }
                .medium { background: #ffc107; color: #000; }
                .low { background: #28a745; }
            </style>
        </head>
        <body>
            <div class='header'>
                <h1>Vulnerability Scan Report</h1>
                <p><strong>Target:</strong> {$scanData['target_url']}</p>
                <p><strong>Scan Type:</strong> " . ucfirst($scanData['scan_type']) . "</p>
                <p><strong>Scan Date:</strong> " . date('Y-m-d H:i:s') . "</p>
            </div>
            
            <h2>Executive Summary</h2>
            <div>
                <div class='summary-card critical'>Critical: {$critical}</div>
                <div class='summary-card high'>High: {$high}</div>
                <div class='summary-card medium'>Medium: {$medium}</div>
                <div class='summary-card low'>Low: {$low}</div>
            </div>
            
            <p><strong>Total Vulnerabilities:</strong> {$total}</p>
            
            <h2>Report Details</h2>
            <p>A detailed PDF report is attached to this email containing:</p>
            <ul>
                <li>Complete vulnerability analysis</li>
                <li>Risk assessment and impact analysis</li>
                <li>Remediation recommendations</li>
                <li>Technical details for each finding</li>
            </ul>
            
            <p><strong>Next Steps:</strong></p>
            <ol>
                <li>Review the attached PDF report</li>
                <li>Prioritize critical and high severity issues</li>
                <li>Implement recommended fixes</li>
                <li>Schedule follow-up scans to verify remediation</li>
            </ol>
            
            <hr>
            <p><em>This is an automated report generated by the Vulnerability Scanner system.</em></p>
            <p><em>If you have any questions, please contact the security team.</em></p>
        </body>
        </html>
        ";
    }
    
    private function sendEmailWithAttachment($recipients, $subject, $body, $attachmentPath) {
        try {
            $attachments = [];
            if (file_exists($attachmentPath)) {
                $attachments[] = [
                    'path' => $attachmentPath,
                    'content_type' => 'application/pdf'
                ];
            }
            
            $result = $this->emailGateway->sendEmail(
                "noreply@petawall.com",
                $recipients,
                $subject,
                $body,
                $attachments
            );
            
            error_log("PDF report email sent via ZeptoMail - Success");
            return true;
            
        } catch (Exception $e) {
            error_log("Email sending failed: " . $e->getMessage());
            return false;
        }
    }
}
?>