<?php
require_once __DIR__ . '/../vendor/autoload.php'; // For TCPDF or Dompdf

class PdfReportGenerator {
    private $pdf;
    
    public function __construct() {
        // Initialize PDF library (using TCPDF as example)
        $this->pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
        $this->setupPdf();
    }
    
    private function setupPdf() {
        // Set document information
        $this->pdf->SetCreator('Vulnerability Scanner');
        $this->pdf->SetAuthor('Security Team');
        $this->pdf->SetTitle('Vulnerability Scan Report');
        $this->pdf->SetSubject('Security Assessment');
        
        // Set default header data
        $this->pdf->SetHeaderData('', 0, 'Vulnerability Scan Report', 'Generated by Security Scanner');
        
        // Set header and footer fonts
        $this->pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
        $this->pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
        
        // Set default monospaced font
        $this->pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
        
        // Set margins
        $this->pdf->SetMargins(15, 25, 15);
        $this->pdf->SetHeaderMargin(10);
        $this->pdf->SetFooterMargin(10);
        
        // Set auto page breaks
        $this->pdf->SetAutoPageBreak(TRUE, 25);
        
        // Set image scale factor
        $this->pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
    }
    
    public function generateVulnerabilityReport($scanData, $results, $outputPath = null) {
        $this->pdf->AddPage();
        
        // Title
        $this->pdf->SetFont('helvetica', 'B', 16);
        $this->pdf->Cell(0, 10, 'Vulnerability Scan Report', 0, 1, 'C');
        $this->pdf->Ln(10);
        
        // Scan Information
        $this->pdf->SetFont('helvetica', 'B', 12);
        $this->pdf->Cell(0, 10, 'Scan Information', 0, 1);
        $this->pdf->SetFont('helvetica', '', 10);
        
        $scanInfo = [
            'Target URL' => $scanData['target_url'],
            'Scan Type' => ucfirst($scanData['scan_type']),
            'Scan Date' => date('Y-m-d H:i:s'),
            'Generated By' => 'Automated Vulnerability Scanner'
        ];
        
        foreach ($scanInfo as $key => $value) {
            $this->pdf->Cell(40, 6, $key . ':', 0, 0);
            $this->pdf->Cell(0, 6, $value, 0, 1);
        }
        
        $this->pdf->Ln(10);
        
        // Vulnerability Summary
        $this->addVulnerabilitySummary($results);
        
        // Detailed Vulnerabilities
        $this->addDetailedVulnerabilities($results);
        
        // Recommendations
        $this->addRecommendations($results);
        
        // Generate file
        if ($outputPath) {
            $filename = $outputPath;
        } else {
            $filename = sys_get_temp_dir() . '/vulnerability_scan_' . uniqid() . '.pdf';
        }
        
        $this->pdf->Output($filename, 'F');
        return $filename;
    }
    
    private function addVulnerabilitySummary($results) {
        $this->pdf->SetFont('helvetica', 'B', 12);
        $this->pdf->Cell(0, 10, 'Vulnerability Summary', 0, 1);
        
        $summary = $results['summary'] ?? [];
        $critical = $summary['critical'] ?? 0;
        $high = $summary['high'] ?? 0;
        $medium = $summary['medium'] ?? 0;
        $low = $summary['low'] ?? 0;
        $total = $critical + $high + $medium + $low;
        
        $this->pdf->SetFont('helvetica', '', 10);
        
        // Summary table
        $html = '
        <table border="1" cellpadding="4" style="border-collapse: collapse;">
            <tr style="background-color: #f8f9fa;">
                <th width="25%">Severity</th>
                <th width="25%">Count</th>
                <th width="50%">Risk Level</th>
            </tr>
            <tr>
                <td><b>Critical</b></td>
                <td>' . $critical . '</td>
                <td style="color: #dc3545;">Immediate attention required</td>
            </tr>
            <tr>
                <td><b>High</b></td>
                <td>' . $high . '</td>
                <td style="color: #fd7e14;">Address as soon as possible</td>
            </tr>
            <tr>
                <td><b>Medium</b></td>
                <td>' . $medium . '</td>
                <td style="color: #ffc107;">Schedule for resolution</td>
            </tr>
            <tr>
                <td><b>Low</b></td>
                <td>' . $low . '</td>
                <td style="color: #28a745;">Consider addressing</td>
            </tr>
            <tr style="background-color: #e9ecef;">
                <td><b>Total</b></td>
                <td><b>' . $total . '</b></td>
                <td></td>
            </tr>
        </table>
        ';
        
        $this->pdf->writeHTML($html, true, false, true, false, '');
        $this->pdf->Ln(10);
    }
    
    private function addDetailedVulnerabilities($results) {
        $vulnerabilities = $results['vulnerabilities'] ?? [];
        
        if (empty($vulnerabilities)) {
            $this->pdf->SetFont('helvetica', 'B', 12);
            $this->pdf->Cell(0, 10, 'No Vulnerabilities Found', 0, 1);
            $this->pdf->SetFont('helvetica', '', 10);
            $this->pdf->Cell(0, 6, 'The scan did not identify any security vulnerabilities.', 0, 1);
            $this->pdf->Ln(10);
            return;
        }
        
        $this->pdf->SetFont('helvetica', 'B', 12);
        $this->pdf->Cell(0, 10, 'Detailed Vulnerabilities', 0, 1);
        
        foreach ($vulnerabilities as $index => $vuln) {
            $severity = strtolower($vuln['severity'] ?? 'unknown');
            $severityColor = $this->getSeverityColor($severity);
            
            $html = '
            <div style="border: 1px solid #ddd; padding: 10px; margin-bottom: 10px; background-color: #f8f9fa;">
                <h3 style="color: ' . $severityColor . '; margin: 0 0 5px 0;">' . ($index + 1) . '. ' . 
                htmlspecialchars($vuln['type'] ?? 'Unknown Type') . ' - ' . strtoupper($severity) . '</h3>
                <p><strong>CVSS Score:</strong> ' . ($vuln['cvss_score'] ?? 'N/A') . '</p>
                <p><strong>Location:</strong> ' . htmlspecialchars($vuln['location'] ?? 'Not specified') . '</p>
                <p><strong>Description:</strong> ' . htmlspecialchars($vuln['description'] ?? 'No description') . '</p>
                <p><strong>Impact:</strong> ' . htmlspecialchars($vuln['impact'] ?? 'Not specified') . '</p>
                <p><strong>Remediation:</strong> ' . htmlspecialchars($vuln['remediation'] ?? 'No remediation provided') . '</p>
            </div>
            ';
            
            $this->pdf->writeHTML($html, true, false, true, false, '');
        }
        
        $this->pdf->Ln(10);
    }
    
    private function addRecommendations($results) {
        $recommendations = $results['recommendations'] ?? [];
        
        if (empty($recommendations)) {
            return;
        }
        
        $this->pdf->AddPage();
        $this->pdf->SetFont('helvetica', 'B', 12);
        $this->pdf->Cell(0, 10, 'Security Recommendations', 0, 1);
        
        $this->pdf->SetFont('helvetica', '', 10);
        
        $html = '<ul>';
        foreach ($recommendations as $rec) {
            $html .= '<li>' . htmlspecialchars($rec) . '</li>';
        }
        $html .= '</ul>';
        
        $this->pdf->writeHTML($html, true, false, true, false, '');
    }
    
    private function getSeverityColor($severity) {
        $colors = [
            'critical' => '#dc3545',
            'high' => '#fd7e14',
            'medium' => '#ffc107',
            'low' => '#28a745',
            'unknown' => '#6c757d'
        ];
        
        return $colors[$severity] ?? '#6c757d';
    }
}
?>